import { Event } from "./types";

export const sampleEvents: Event[] = [
  {
    id: "1",
    title: "Design Systems Summit 2026",
    description: "A full-day conference exploring the future of design systems, component libraries, and cross-platform consistency.",
    date: "2026-03-15",
    time: "09:00",
    location: "The Grand Hall, San Francisco",
    category: "conference",
    attendees: 142,
    maxAttendees: 300,
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    status: "upcoming",
  },
  {
    id: "2",
    title: "Watercolor & Wine Evening",
    description: "An intimate evening of guided watercolor painting paired with curated wines from local vineyards.",
    date: "2026-03-08",
    time: "18:30",
    location: "Studio Amber, Brooklyn",
    category: "social",
    attendees: 18,
    maxAttendees: 24,
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80",
    status: "upcoming",
  },
  {
    id: "3",
    title: "React Advanced Workshop",
    description: "Deep dive into React Server Components, Suspense patterns, and performance optimization techniques.",
    date: "2026-03-20",
    time: "10:00",
    location: "TechHub, Austin",
    category: "workshop",
    attendees: 35,
    maxAttendees: 40,
    image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&q=80",
    status: "upcoming",
  },
  {
    id: "4",
    title: "Founder's Circle Mixer",
    description: "Connect with fellow founders, investors, and mentors over cocktails and canapés.",
    date: "2026-04-02",
    time: "19:00",
    location: "Rooftop Terrace, Manhattan",
    category: "networking",
    attendees: 56,
    maxAttendees: 80,
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&q=80",
    status: "upcoming",
  },
  {
    id: "5",
    title: "Spring Gala 2026",
    description: "An elegant evening celebrating the arts with live music, gourmet dining, and a silent auction.",
    date: "2026-04-12",
    time: "18:00",
    location: "The Crystal Ballroom, Chicago",
    category: "celebration",
    attendees: 200,
    maxAttendees: 350,
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80",
    status: "upcoming",
  },
  {
    id: "6",
    title: "UX Research Bootcamp",
    description: "Two-day intensive bootcamp covering user interviews, usability testing, and data synthesis.",
    date: "2026-03-28",
    time: "09:00",
    location: "Innovation Lab, Seattle",
    category: "workshop",
    attendees: 22,
    maxAttendees: 30,
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80",
    status: "upcoming",
  },
];
